apiVersion: v1
kind: Pod
metadata:
  name: cryptojacking
spec:
  containers:
  - name: miner
    image: ubuntu
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      privileged: true  # Akses penuh ke host (Berbahaya!)
    stdin: true
    tty: true
